/**
 * Standard error codes for agent proposals and execution outcomes.
 */
export enum ProposalErrorCode {
    // Schema & Versioning
    INVALID_JSON = "INVALID_JSON",
    SCHEMA_VERSION_INCOMPATIBLE = "SCHEMA_VERSION_INCOMPATIBLE",
    VALIDATION_ERROR = "VALIDATION_ERROR",

    // Policy & Authorization
    ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED",
    POLICY_VIOLATION = "POLICY_VIOLATION",

    // Execution
    EXECUTION_ERROR = "EXECUTION_ERROR",
    FILE_NOT_FOUND = "FILE_NOT_FOUND",

    // Existing / Legacy
    NULL_BYTE = "NULL_BYTE",
    INVALID_ASCII = "INVALID_ASCII",
    PAYLOAD_OVERFLOW = "PAYLOAD_OVERFLOW",
    ID_COLLISION = "ID_COLLISION",
    INVALID_CONTENT = "INVALID_CONTENT",
    MISSING_CONTENT = "MISSING_CONTENT",
}

export enum RuntimeErrorId {
    // Schema Validation
    PATH_MISSING = "PATH_MISSING",
    PATH_NOT_STRING = "PATH_NOT_STRING",
    PATH_OUT_OF_BOUNDS = "PATH_OUT_OF_BOUNDS",

    // Read & Inspection
    PATH_NOT_FOUND = "PATH_NOT_FOUND",
    IS_DIRECTORY = "IS_DIRECTORY",
    NOT_A_DIRECTORY = "NOT_A_DIRECTORY",

    // State Modification
    ALREADY_EXISTS = "ALREADY_EXISTS",
    DISK_FULL = "DISK_FULL",
    IO_ERROR = "IO_ERROR",

    // High-Risk Operations
    FILE_NOT_FOUND = "FILE_NOT_FOUND",
    PERMISSION_DENIED = "PERMISSION_DENIED",
    TARGET_ALREADY_EXISTS = "TARGET_ALREADY_EXISTS",

    // Fallback
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}
